### ISSUE TITLE
您好，请教个问题

### ISSUE THREAD

**Issue by Superzzw1994** [bozhouyongqi/debug-react#1]
Failed to load plugin 'no-for-of-loops' declared in 'src/react/.eslintrc.js': Cannot find module 'eslint-plugin-no-for-of-loops'

在react下yarn install 总在Fetching packages 时候卡住，请问有解决的办法吗？

**Comment by bozhouyongqi** [comment]
你说yarn add eslint-plugin-no-for-of-loops -D这个会卡住吗？是不是网络原因？或者你试试tnpm能否装上？
8-11中的错误都是react eslint中的错误，可以试试在webpack.config.js中删除eslint插件。就不会报这些错误了
